name = "artificial-aggrerator"
main = "src/index.ts"
compatibility_date = "2025-04-01"
routes = [
  { pattern = "artificialaggregator.com", custom_domain = true },
  { pattern = "www.artificialaggregator.com", custom_domain = true },
]

[triggers]
crons = ["0 * * * *"]

[vars]
AA_SOURCE_URL = "https://artificialanalysis.ai/models"

[assets]
directory = "public"
binding = "ASSETS"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[[d1_databases]]
binding = "DB"
database_name = "artificial-aggregator"
database_id = "1552c045-0b03-41ed-8df8-bd189497e007"
migrations_dir = "drizzle"
